Update docker image

diff --git a/docker/prod/deployment/healthcheck b/docker/prod/deployment/healthcheck
--- a/docker/prod/deployment/healthcheck
+++ b/docker/prod/deployment/healthcheck
@@ -22,6 +22,13 @@ elif [ "${container_mode}" = "reverb" ]; then
         echo "Healthcheck failed."
         exit 1
     fi
+elif [ "${container_mode}" = "ssr" ]; then
+    if [ "$(supervisorctl status inertia-ssr-server:inertia-ssr-server_0 | awk '{print tolower($2)}')" = "running" ]; then
+        exit 0
+    else
+        echo "Healthcheck failed."
+        exit 1
+    fi
 elif [ "${container_mode}" = "worker" ]; then
     if [ "$(supervisorctl status worker:worker_0 | awk '{print tolower($2)}')" = "running" ]; then
         exit 0
